language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - joaquin_z619@hotmail.com
script:
# Test unitario y de integracion en develop con cobertura
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify --settings settings.xml
# Cobertura es subida a SonarCloud
- mvn sonar:sonar -Dsonar.organization=joaquin-z-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1dbbc889b09d3685b8a78e42f930ccfa3a613645 --settings settings.xml
